fe: fe::Lexer< K, S > Class Template Reference
fe::Lexer< K, S > Class Template Reference
The blueprint for a lexer with a buffer of K tokens to peek into the future (Lexer::ahead).
#include <fe/lexer.h>
Public Member Functions
Lexer (std::istream &istream, const std::filesystem::path *path=nullptr)
Loc loc () const
Protected Member Functions
char32_t ahead (size_t i=0) const
void begin ()
Invoke before assembling the next token.
char32_t next ()
Get next char32_t in Lexer::istream_ and increase Lexer::loc_.
Protected Attributes
std::istream & istream_
Ring< char32_t, K > ahead_
Loc loc_
Location of the token we are currently constructing within Lexer::str_,.
Pos peek_
Position of ahead_::first;.
std::string str_
accept
enum class Append {
Off ,
On ,
Lower ,
Upper
}
What should happend to the accepted char?
template<Append append = Append::On, class Pred >
bool accept_if (Pred pred)
template<Append append = Append::On>
bool accept (char32_t c)
Detailed Description
template<size_t K, class S>
class fe::Lexer< K, S >
The blueprint for a lexer with a buffer of K tokens to peek into the future (Lexer::ahead).
You can "overide" Lexer::next via CRTP (S is the child).
Definition at line 14 of file lexer.h.
Member Enumeration Documentation
Append
template<size_t K, class S > enum class fe::Lexer::Append strong protected
What should happend to the accepted char?
Enumerator
Off
Do not append accepted char to Lexer::str_.
On
Append accepted char as is to Lexer::str_.
Lower
Append accepted char via std::tolower to Lexer::str_.
Upper
Append accepted char via std::toupper to Lexer::str_.
Definition at line 61 of file lexer.h.
Constructor & Destructor Documentation
Lexer()
template<size_t K, class S > fe::Lexer< K, S >::Lexer (std::istream & istream, const std::filesystem::path * path = nullptr) inline
Definition at line 20 of file lexer.h.
Member Function Documentation
accept()
template<size_t K, class S > template<Append append = Append::On> bool fe::Lexer< K, S >::accept (char32_t c) inline protected
Definition at line 83 of file lexer.h.
accept_if()
template<size_t K, class S > template<Append append = Append::On, class Pred > bool fe::Lexer< K, S >::accept_if (Pred pred) inline protected
Returns
true if pred holds. In this case invoke Lexer::next() and append to Lexer::str_, if append.
Definition at line 70 of file lexer.h.
References fe::Lexer< K, S >::ahead(), fe::Lexer< K, S >::Lower, fe::Lexer< K, S >::Off, fe::Lexer< K, S >::str_, and fe::Lexer< K, S >::Upper.
ahead()
template<size_t K, class S > char32_t fe::Lexer< K, S >::ahead (size_t i = 0) const inline protected
Definition at line 31 of file lexer.h.
References fe::Lexer< K, S >::ahead_.
Referenced by fe::Lexer< K, S >::accept_if(), and fe::Lexer< K, S >::next().
begin()
template<size_t K, class S > void fe::Lexer< K, S >::begin () inline protected
Invoke before assembling the next token.
Definition at line 34 of file lexer.h.
References fe::Loc::begin, fe::Lexer< K, S >::loc_, fe::Lexer< K, S >::peek_, and fe::Lexer< K, S >::str_.
loc()
template<size_t K, class S > Loc fe::Lexer< K, S >::loc () const inline
Definition at line 28 of file lexer.h.
References fe::Lexer< K, S >::loc_.
next()
template<size_t K, class S > char32_t fe::Lexer< K, S >::next () inline protected
Get next char32_t in Lexer::istream_ and increase Lexer::loc_.
Returns
0 on an invalid UTF-8 sequence.
Definition at line 41 of file lexer.h.
References fe::Lexer< K, S >::ahead(), fe::Lexer< K, S >::ahead_, fe::Pos::col, fe::utf8::decode(), fe::utf8::EoF, fe::Loc::finis, fe::Lexer< K, S >::istream_, fe::Lexer< K, S >::loc_, fe::Lexer< K, S >::peek_, fe::Ring< T, N >::put(), and fe::Pos::row.
Member Data Documentation
ahead_
template<size_t K, class S > Ring<char32_t, K> fe::Lexer< K, S >::ahead_ protected
Definition at line 89 of file lexer.h.
Referenced by fe::Lexer< K, S >::ahead(), and fe::Lexer< K, S >::next().
istream_
template<size_t K, class S > std::istream& fe::Lexer< K, S >::istream_ protected
Definition at line 88 of file lexer.h.
Referenced by fe::Lexer< K, S >::next().
loc_
template<size_t K, class S > Loc fe::Lexer< K, S >::loc_ protected
Location of the token we are currently constructing within Lexer::str_,.
Definition at line 90 of file lexer.h.
Referenced by fe::Lexer< K, S >::begin(), fe::Lexer< K, S >::loc(), and fe::Lexer< K, S >::next().
peek_
template<size_t K, class S > Pos fe::Lexer< K, S >::peek_ protected
Position of ahead_::first;.
Definition at line 91 of file lexer.h.
Referenced by fe::Lexer< K, S >::begin(), and fe::Lexer< K, S >::next().
str_
template<size_t K, class S > std::string fe::Lexer< K, S >::str_ protected
Definition at line 92 of file lexer.h.
Referenced by fe::Lexer< K, S >::accept_if(), and fe::Lexer< K, S >::begin().
The documentation for this class was generated from the following file:
fe/lexer.h