FE: fe::Arena< A, P >::Allocator< T > Struct Template Reference
fe::Arena< A, P >::Allocator< T > Struct Template Reference
An allocator.
#include <fe/arena.h>
Public Types
using value_type = T
Public Member Functions
Allocator () noexcept=delete
template<class U >
Allocator (const Arena< A, P >::Allocator< U > &allocator) noexcept
Allocator (Arena< A, P > &arena) noexcept
T * allocate (size_t n)
void deallocate (T *, size_t) noexcept
template<class U >
bool operator== (const Allocator< U > &a) const noexcept
template<class U >
bool operator!= (const Allocator< U > &a) const noexcept
Public Attributes
Arena< A, P > & arena
Detailed Description
template<size_t A = sizeof(size_t), size_t P = Default_Page_Size>
template<class T>
struct fe::Arena< A, P >::Allocator< T >
An allocator.
Construct one via Arena::allocator.
Definition at line 29 of file arena.h.
Member Typedef Documentation
value_type
template<size_t A = sizeof(size_t), size_t P = Default_Page_Size> template<class T > using fe::Arena< A, P >::Allocator< T >::value_type = T
Definition at line 30 of file arena.h.
Constructor & Destructor Documentation
Allocator() [1/3]
template<size_t A = sizeof(size_t), size_t P = Default_Page_Size> template<class T > fe::Arena< A, P >::Allocator< T >::Allocator () delete noexcept
Allocator() [2/3]
template<size_t A = sizeof(size_t), size_t P = Default_Page_Size> template<class T > template<class U > fe::Arena< A, P >::Allocator< T >::Allocator (const Arena< A, P >::Allocator< U > & allocator) inline noexcept
Definition at line 34 of file arena.h.
Allocator() [3/3]
template<size_t A = sizeof(size_t), size_t P = Default_Page_Size> template<class T > fe::Arena< A, P >::Allocator< T >::Allocator (Arena< A, P > & arena) inline noexcept
Definition at line 36 of file arena.h.
Member Function Documentation
allocate()
template<size_t A = sizeof(size_t), size_t P = Default_Page_Size> template<class T > T * fe::Arena< A, P >::Allocator< T >::allocate (size_t n) inline
Definition at line 39 of file arena.h.
References fe::Arena< A, P >::allocate(), and fe::Arena< A, P >::Allocator< T >::arena.
deallocate()
template<size_t A = sizeof(size_t), size_t P = Default_Page_Size> template<class T > void fe::Arena< A, P >::Allocator< T >::deallocate (T * , size_t) inline noexcept
Definition at line 44 of file arena.h.
operator!=()
template<size_t A = sizeof(size_t), size_t P = Default_Page_Size> template<class T > template<class U > bool fe::Arena< A, P >::Allocator< T >::operator!= (const Allocator< U > & a) const inline noexcept
Definition at line 47 of file arena.h.
References fe::Arena< A, P >::Allocator< T >::arena.
operator==()
template<size_t A = sizeof(size_t), size_t P = Default_Page_Size> template<class T > template<class U > bool fe::Arena< A, P >::Allocator< T >::operator== (const Allocator< U > & a) const inline noexcept
Definition at line 46 of file arena.h.
References fe::Arena< A, P >::Allocator< T >::arena.
Member Data Documentation
arena
template<size_t A = sizeof(size_t), size_t P = Default_Page_Size> template<class T > Arena<A, P>& fe::Arena< A, P >::Allocator< T >::arena
Definition at line 49 of file arena.h.
Referenced by fe::Arena< A, P >::Allocator< T >::allocate(), fe::Arena< A, P >::Allocator< T >::operator!=(), and fe::Arena< A, P >::Allocator< T >::operator==().
The documentation for this struct was generated from the following file:
fe/arena.h