add_executable(fe-test)
target_sources(fe-test
    PRIVATE
        bitset.cpp
        cast.cpp
        cli.cpp
        hash.cpp
        lexer.cpp
        loc.cpp
        test.cpp
        xtrie.cpp
)
target_link_libraries(fe-test
    PRIVATE
        fe-lib
        doctest::doctest
)
include(../submodules/doctest/scripts/cmake/doctest.cmake)
doctest_discover_tests(fe-test)
