add_executable(fe-test)
target_sources(fe-test
    PRIVATE
        cast.cpp
        hash.cpp
        lexer.cpp
        loc.cpp
        snippet.cpp
        test.cpp
)
target_link_libraries(fe-test
    PRIVATE
        fe
        doctest::doctest
)
include(../submodules/doctest/scripts/cmake/doctest.cmake)
doctest_discover_tests(fe-test)
