name: doxygen

on:
  push:
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    name: Build and deploy Doxygen documentation
    runs-on: ubuntu-latest

    steps:
    - name: Clone recursively
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install documentation dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ghostscript graphviz texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

    - name: Install Doxygen
      run: |
        wget https://www.doxygen.nl/files/doxygen-1.16.1.linux.bin.tar.gz
        tar xf doxygen-1.16.1.linux.bin.tar.gz

    - name: Configure
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DFE_BUILD_DOCS=ON -DDOXYGEN_EXECUTABLE=${{github.workspace}}/doxygen-1.16.1/bin/doxygen

    - name: Build
      run: cmake --build ${{github.workspace}}/build -v --target docs

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{github.workspace}}/build/html
