name: linux

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and test ${{matrix.build-type}} mode
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [Debug, Release]

    steps:
      - name: Clone recursively
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: Configure
        run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DBUILD_TESTING=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build -v

      - name: Test with Valgrind
        run: valgrind --error-exitcode=1 --leak-check=full ${{github.workspace}}/build/bin/fe-test
