name: macos

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and test ${{matrix.build-type}} mode
    runs-on: macos-13
    strategy:
      matrix:
        build-type: [Debug, Release]

    steps:
      - name: Clone recursively
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install LLVM and Clang
        run: brew install llvm@16

      - name: Configure
        run: |
          CXX="/usr/local/opt/llvm@16/bin/clang++" \
          CXXFLAGS="-stdlib=libc++ -fexperimental-library" \
          LDFLAGS="-L/usr/local/opt/llvm@16/lib/c++ -Wl,-rpath,/usr/local/opt/llvm@16/lib/c++" \
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DBUILD_TESTING=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build -v

      - name: Test
        run: ${{github.workspace}}/build/bin/fe-test
