name: windows

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and test ${{matrix.build-type}} mode
    runs-on: windows-2022
    strategy:
      matrix:
        build-type: [Debug, Release]

    steps:
      - name: Clone recursively
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DBUILD_TESTING=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build -v

      - name: Test
        run: ctest --test-dir ${{github.workspace}}/build --output-on-failure
